# media/services/storage_base.py
from typing import BinaryIO, Protocol

class Storage(Protocol):
    def save(self, key: str, stream: BinaryIO, size: int, content_type: str) -> None: ...
    def open(self, key: str) -> BinaryIO: ...
    def exists(self, key: str) -> bool: ...
    def url(self, key: str, expires: int = 3600) -> str: ...
