"""empty message

Revision ID: f4025012f039
Revises: b8239d03db7d
Create Date: 2025-09-08 18:35:59.540542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4025012f039'
down_revision = 'b8239d03db7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=16), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('storage', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_geo', sa.Boolean(), nullable=False),
    sa.Column('crs', sa.String(length=128), nullable=True),
    sa.Column('bounds', sa.JSON(), nullable=True),
    sa.Column('transform', sa.JSON(), nullable=True),
    sa.Column('mpp', sa.Float(), nullable=True),
    sa.Column('exif', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'size_bytes', name='uq_asset_dedup')
    )
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_asset_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_uuid'), ['uuid'], unique=True)

    op.create_table('media_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_variant_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_variant_asset_id'))

    op.drop_table('media_variant')
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_asset_uuid'))
        batch_op.drop_index(batch_op.f('ix_media_asset_sha256'))

    op.drop_table('media_asset')
    # ### end Alembic commands ###
